In [53]:
import pandas as pd
import numpy as np
import keras as kr

data = pd.read_csv('earthquakes_scaled_class.csv', index_col="index")

data = data.drop("index.1", axis=1)

data

magnitude      time   updated         felt  cdi  mmi  tsunami  \
index                                                                       
us6000lcz2          5 -0.815799 -0.977412    -0.083333 -0.6 -1.0      0.0   
us6000n9xs          4  0.289580  0.000423    -0.083333 -0.6  0.0      0.0   
tx2024mydx          4  0.289510  0.349996    -0.083333 -0.6  0.0      0.0   
us6000n9xf          4  0.289510  0.000343    -0.083333 -0.6  0.0      0.0   
nn00880145          4  0.278268  0.311118    -0.083333 -0.6 -1.0      0.0   
...               ...       ...       ...          ...  ...  ...      ...   
ci40731623          5  0.580644  0.377703   774.583333  0.4  1.0      1.0   
ci40699207          4  0.455449  0.368965  1009.375000  0.4  1.0      1.0   
ci40699207          4  0.455449  0.368965  1009.375000  0.4  1.0      1.0   
ok2024cish          5 -0.323356  0.356419  1101.333333  0.8  3.0      0.0   
ok2024cish          5 -0.323356  0.356419  1101.333333  0.8  3.0      0.0   

                 sig       nst      dmin  ...       gap  magType     depth  \
index                                     ...                                
us6000lcz2  0.000000  0.491667  1.290504  ...  0.105263     0.25  0.000000   
us6000n9xs -0.919014 -0.608333 -0.232505  ...  1.526316    -0.75  0.001914   
tx2024mydx -0.838028 -0.583333 -0.295730  ...  0.315789    -0.75 -0.149192   
us6000n9xf -0.799296 -0.608333 -0.228936  ...  1.657895    -0.75 -0.043131   
nn00880145 -0.919014 -0.775000  0.137667  ...  0.022105    -0.75 -0.092003   
...              ...       ...       ...  ...       ...      ...       ...   
ci40731623  1.299296  0.358333 -0.330208  ...  1.368421    -0.50  0.049682   
ci40699207  1.362676  0.750000 -0.329897  ... -0.657895    -0.50  0.036065   
ci40699207  1.362676  0.750000 -0.329897  ... -0.657895    -0.50  0.036065   
ok2024cish  2.235915 -0.316667 -0.346718  ...  1.289474     0.25 -0.257609   
ok2024cish  2.235915 -0.316667 -0.346718  ...  1.289474     0.25 -0.257609   

            latitude  longitude  distanceKM  continent   country  subnational  \
index                                                                           
us6000lcz2 -0.126122   0.902897   -0.804348        0.5  0.275862     0.129630   
us6000n9xs  0.000000  -0.153676    0.369565        0.0  0.000000     0.000000   
tx2024mydx  0.000098  -0.153676    0.369565        0.0  0.000000     0.000000   
us6000n9xf  0.000601  -0.153707    0.391304        0.0  0.000000     0.000000   
nn00880145  0.580415  -0.207513   -0.086957        0.0  0.000000    -0.666667   
...              ...        ...         ...        ...       ...          ...   
ci40731623  0.180617  -0.216912   -0.673913        0.0  0.000000    -1.555556   
ci40699207  0.181669  -0.214216   -0.717391        0.0  0.000000    -1.555556   
ci40699207  0.181669  -0.214216   -0.717391        0.0  0.000000    -1.555556   
ok2024cish  0.290674  -0.121519   -0.630435        0.0  0.000000    -0.537037   
ok2024cish  0.290674  -0.121519   -0.630435        0.0  0.000000    -0.537037   

                city  
index                 
us6000lcz2  0.234432  
us6000n9xs  0.000000  
tx2024mydx  0.000000  
us6000n9xf  0.000000  
nn00880145 -2.021978  
...              ...  
ci40731623 -0.952381  
ci40699207 -0.952381  
ci40699207 -0.952381  
ok2024cish -0.556777  
ok2024cish -0.556777  

[1136 rows x 21 columns]

In [54]:
data["magnitude"].unique()

array([5, 4, 3, 6, 7, 8], dtype=int64)

In [55]:
model = kr.models.Sequential()

model.add(kr.layers.Dense(50, input_dim=20, activation="relu", kernel_initializer="he_normal"))
model.add(kr.layers.BatchNormalization())
model.add(kr.layers.Dense(100, activation="relu", kernel_initializer="he_normal"))
model.add(kr.layers.BatchNormalization())
model.add(kr.layers.Dense(150, activation="relu", kernel_initializer="he_normal"))
model.add(kr.layers.BatchNormalization())
model.add(kr.layers.Dense(250, activation="relu", kernel_initializer="he_normal"))
model.add(kr.layers.BatchNormalization())
model.add(kr.layers.Dense(100, activation="relu", kernel_initializer="he_normal"))
model.add(kr.layers.BatchNormalization())
model.add(kr.layers.Dense(6, activation="softmax", kernel_initializer="he_normal"))

model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

C:\Users\mario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [56]:
data["magnitude"] = data["magnitude"].map(lambda x: x - 3)
data

magnitude      time   updated         felt  cdi  mmi  tsunami  \
index                                                                       
us6000lcz2          2 -0.815799 -0.977412    -0.083333 -0.6 -1.0      0.0   
us6000n9xs          1  0.289580  0.000423    -0.083333 -0.6  0.0      0.0   
tx2024mydx          1  0.289510  0.349996    -0.083333 -0.6  0.0      0.0   
us6000n9xf          1  0.289510  0.000343    -0.083333 -0.6  0.0      0.0   
nn00880145          1  0.278268  0.311118    -0.083333 -0.6 -1.0      0.0   
...               ...       ...       ...          ...  ...  ...      ...   
ci40731623          2  0.580644  0.377703   774.583333  0.4  1.0      1.0   
ci40699207          1  0.455449  0.368965  1009.375000  0.4  1.0      1.0   
ci40699207          1  0.455449  0.368965  1009.375000  0.4  1.0      1.0   
ok2024cish          2 -0.323356  0.356419  1101.333333  0.8  3.0      0.0   
ok2024cish          2 -0.323356  0.356419  1101.333333  0.8  3.0      0.0   

                 sig       nst      dmin  ...       gap  magType     depth  \
index                                     ...                                
us6000lcz2  0.000000  0.491667  1.290504  ...  0.105263     0.25  0.000000   
us6000n9xs -0.919014 -0.608333 -0.232505  ...  1.526316    -0.75  0.001914   
tx2024mydx -0.838028 -0.583333 -0.295730  ...  0.315789    -0.75 -0.149192   
us6000n9xf -0.799296 -0.608333 -0.228936  ...  1.657895    -0.75 -0.043131   
nn00880145 -0.919014 -0.775000  0.137667  ...  0.022105    -0.75 -0.092003   
...              ...       ...       ...  ...       ...      ...       ...   
ci40731623  1.299296  0.358333 -0.330208  ...  1.368421    -0.50  0.049682   
ci40699207  1.362676  0.750000 -0.329897  ... -0.657895    -0.50  0.036065   
ci40699207  1.362676  0.750000 -0.329897  ... -0.657895    -0.50  0.036065   
ok2024cish  2.235915 -0.316667 -0.346718  ...  1.289474     0.25 -0.257609   
ok2024cish  2.235915 -0.316667 -0.346718  ...  1.289474     0.25 -0.257609   

            latitude  longitude  distanceKM  continent   country  subnational  \
index                                                                           
us6000lcz2 -0.126122   0.902897   -0.804348        0.5  0.275862     0.129630   
us6000n9xs  0.000000  -0.153676    0.369565        0.0  0.000000     0.000000   
tx2024mydx  0.000098  -0.153676    0.369565        0.0  0.000000     0.000000   
us6000n9xf  0.000601  -0.153707    0.391304        0.0  0.000000     0.000000   
nn00880145  0.580415  -0.207513   -0.086957        0.0  0.000000    -0.666667   
...              ...        ...         ...        ...       ...          ...   
ci40731623  0.180617  -0.216912   -0.673913        0.0  0.000000    -1.555556   
ci40699207  0.181669  -0.214216   -0.717391        0.0  0.000000    -1.555556   
ci40699207  0.181669  -0.214216   -0.717391        0.0  0.000000    -1.555556   
ok2024cish  0.290674  -0.121519   -0.630435        0.0  0.000000    -0.537037   
ok2024cish  0.290674  -0.121519   -0.630435        0.0  0.000000    -0.537037   

                city  
index                 
us6000lcz2  0.234432  
us6000n9xs  0.000000  
tx2024mydx  0.000000  
us6000n9xf  0.000000  
nn00880145 -2.021978  
...              ...  
ci40731623 -0.952381  
ci40699207 -0.952381  
ci40699207 -0.952381  
ok2024cish -0.556777  
ok2024cish -0.556777  

[1136 rows x 21 columns]

In [57]:
print(data[data["magnitude"] == 0].shape, data[data["magnitude"] == 1].shape, data[data["magnitude"] == 2].shape, 
      data[data["magnitude"] == 3].shape, data[data["magnitude"] == 4].shape, data[data["magnitude"] == 5].shape)   

(128, 21) (323, 21) (267, 21) (389, 21) (24, 21) (5, 21)


In [61]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(data, test_size=0.15, random_state=40, stratify=data["magnitude"])

train_x = train.drop("magnitude", axis=1)
train_y = train["magnitude"]

test_x = test.drop("magnitude", axis=1)
test_y = test["magnitude"]

model.fit(train_x, pd.get_dummies(train_y), epochs=500, batch_size=48)

Epoch 1/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9715 - loss: 0.0997
Epoch 2/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9638 - loss: 0.0991
Epoch 3/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9677 - loss: 0.0847 
Epoch 4/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9716 - loss: 0.0798 
Epoch 5/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9767 - loss: 0.0518 
Epoch 6/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9718 - loss: 0.0736 
Epoch 7/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9840 - loss: 0.0545
Epoch 8/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9789 - loss: 0.0698
Epoch 9/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9690 - loss: 0.0678
Epoch 10/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9780 - loss: 0.0572 
Epoch 11/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9793 - loss: 0.0624
Epoch 12/500
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accu

In [62]:
model.evaluate(test_x, pd.get_dummies(test_y))

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9639 - loss: 0.1032  


[0.09418953955173492, 0.9649122953414917]

In [63]:
#I want to predict the classes of the test data

predictions = model.predict(test_x)

predictions = np.argmax(predictions, axis=1)

predictions

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


array([1, 1, 3, 2, 3, 0, 3, 3, 2, 1, 1, 3, 1, 3, 1, 2, 3, 3, 0, 2, 1, 3,
       1, 1, 0, 0, 0, 2, 3, 1, 2, 3, 3, 1, 1, 5, 4, 0, 2, 1, 2, 1, 1, 3,
       3, 0, 1, 1, 2, 3, 2, 3, 0, 3, 3, 1, 1, 0, 1, 3, 3, 1, 3, 2, 3, 0,
       1, 3, 2, 2, 3, 3, 3, 1, 3, 2, 3, 3, 2, 1, 2, 3, 3, 2, 0, 1, 1, 4,
       3, 2, 1, 1, 3, 2, 3, 1, 1, 1, 1, 3, 1, 0, 2, 1, 2, 4, 1, 3, 2, 3,
       0, 2, 1, 1, 3, 3, 3, 0, 2, 1, 1, 3, 3, 3, 1, 2, 2, 1, 2, 3, 2, 2,
       3, 2, 3, 1, 2, 2, 3, 3, 3, 1, 3, 0, 1, 2, 3, 3, 0, 1, 3, 1, 2, 1,
       2, 4, 2, 1, 2, 3, 3, 0, 1, 2, 3, 3, 2, 1, 0, 3, 3], dtype=int64)

In [64]:
#I want a confusion matrix
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(test_y, np.argmax(model.predict(test_x), axis=1))
conf_matrix

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


array([[18,  1,  0,  0,  0,  0],
       [ 0, 48,  1,  0,  0,  0],
       [ 0,  1, 37,  2,  0,  0],
       [ 0,  0,  1, 57,  0,  0],
       [ 0,  0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  0,  1]], dtype=int64)